import type { Sql } from './connection.js';
import { createLogger } from '@context-workspace/shared';

const log = createLogger({ component: 'migrations' });

/**
 * PostgreSQL migrations — append-only, ordered.
 *
 * Each migration is a string of SQL. Migrations are applied in order
 * and tracked in the schema_migrations table.
 *
 * All tables are in the 'public' schema unless noted.
 *
 * Design notes:
 * - UUIDs are used for all primary keys (generated by application, not DB)
 * - All timestamps are BIGINT milliseconds (matches local SQLite convention)
 * - JSONB for all payload/metadata fields
 * - Indexes are created separately for clarity
 */
const MIGRATIONS: { id: number; name: string; sql: string }[] = [
  {
    id: 1,
    name: 'create_schema_migrations',
    sql: `
      CREATE TABLE IF NOT EXISTS schema_migrations (
        id         INTEGER PRIMARY KEY,
        name       TEXT NOT NULL,
        applied_at BIGINT NOT NULL
      );
    `,
  },
  {
    id: 2,
    name: 'create_workspaces',
    sql: `
      CREATE TABLE IF NOT EXISTS workspaces (
        id         TEXT PRIMARY KEY,
        name       TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL
      );
    `,
  },
  {
    id: 3,
    name: 'create_repositories',
    sql: `
      CREATE TABLE IF NOT EXISTS repositories (
        id           TEXT PRIMARY KEY,
        workspace_id TEXT NOT NULL REFERENCES workspaces(id),
        name         TEXT NOT NULL,
        root_path    TEXT NOT NULL,
        status       TEXT NOT NULL DEFAULT 'active',
        created_at   BIGINT NOT NULL,
        updated_at   BIGINT NOT NULL,
        UNIQUE (workspace_id, root_path)
      );
      CREATE INDEX IF NOT EXISTS idx_repositories_workspace ON repositories(workspace_id);
    `,
  },
  {
    id: 4,
    name: 'create_capsules',
    sql: `
      CREATE TABLE IF NOT EXISTS capsules (
        id            TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL REFERENCES repositories(id),
        name          TEXT NOT NULL,
        status        TEXT NOT NULL DEFAULT 'active',
        created_at    BIGINT NOT NULL,
        updated_at    BIGINT NOT NULL,
        archived_at   BIGINT
      );
      CREATE INDEX IF NOT EXISTS idx_capsules_repository ON capsules(repository_id);
    `,
  },
  {
    id: 5,
    name: 'create_events',
    sql: `
      CREATE TABLE IF NOT EXISTS events (
        event_id        TEXT PRIMARY KEY,
        workspace_id    TEXT NOT NULL,
        repository_id   TEXT NOT NULL,
        capsule_id      TEXT,
        session_id      TEXT,
        type            TEXT NOT NULL,
        source          TEXT NOT NULL,
        agent_id        TEXT,
        user_id         TEXT,
        device_id       TEXT,
        client_sequence BIGINT NOT NULL,
        server_sequence BIGINT,
        timestamp       BIGINT NOT NULL,
        visibility      TEXT NOT NULL,
        payload         JSONB NOT NULL,
        payload_hash    TEXT NOT NULL,
        raw_ref         TEXT,
        chunk_id        TEXT,
        chunk_offset    BIGINT,
        chunk_length    BIGINT,
        synced_at       BIGINT,
        created_at      BIGINT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_events_repository ON events(repository_id, timestamp DESC);
      CREATE INDEX IF NOT EXISTS idx_events_capsule ON events(capsule_id, timestamp DESC) WHERE capsule_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_events_type ON events(repository_id, type, timestamp DESC);
      CREATE INDEX IF NOT EXISTS idx_events_hash ON events(payload_hash);
    `,
  },
  {
    id: 6,
    name: 'create_context_objects',
    sql: `
      CREATE TABLE IF NOT EXISTS context_objects (
        id            TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL,
        capsule_id    TEXT,
        type          TEXT NOT NULL,
        scope         TEXT NOT NULL,
        status        TEXT NOT NULL,
        authority     TEXT NOT NULL,
        visibility    TEXT NOT NULL,
        resource      TEXT,
        content       JSONB NOT NULL,
        valid_until   BIGINT,
        version       INTEGER NOT NULL DEFAULT 1,
        created_at    BIGINT NOT NULL,
        updated_at    BIGINT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_ctx_objects_repository ON context_objects(repository_id, type, status);
      CREATE INDEX IF NOT EXISTS idx_ctx_objects_capsule ON context_objects(capsule_id, type) WHERE capsule_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_ctx_objects_resource ON context_objects(resource) WHERE resource IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_ctx_objects_updated ON context_objects(repository_id, updated_at DESC);
    `,
  },
  {
    id: 7,
    name: 'create_context_objects_fts',
    sql: `
      CREATE EXTENSION IF NOT EXISTS pg_trgm;
      CREATE INDEX IF NOT EXISTS idx_ctx_objects_fts ON context_objects
        USING gin(to_tsvector('english', content::text));
    `,
  },
  {
    id: 8,
    name: 'create_relations',
    sql: `
      CREATE TABLE IF NOT EXISTS relations (
        id            TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL,
        from_id       TEXT NOT NULL,
        relation_type TEXT NOT NULL,
        to_id         TEXT NOT NULL,
        created_at    BIGINT NOT NULL,
        metadata      JSONB
      );
      CREATE INDEX IF NOT EXISTS idx_relations_from ON relations(from_id, relation_type);
      CREATE INDEX IF NOT EXISTS idx_relations_to ON relations(to_id, relation_type);
    `,
  },
  {
    id: 9,
    name: 'create_live_state',
    sql: `
      CREATE TABLE IF NOT EXISTS live_state (
        key           TEXT NOT NULL,
        repository_id TEXT NOT NULL,
        value         JSONB NOT NULL,
        updated_at    BIGINT NOT NULL,
        PRIMARY KEY   (repository_id, key)
      );
    `,
  },
  {
    id: 10,
    name: 'create_leases',
    sql: `
      CREATE TABLE IF NOT EXISTS leases (
        id            TEXT PRIMARY KEY,
        repository_id TEXT NOT NULL,
        resource      TEXT NOT NULL,
        holder_id     TEXT NOT NULL,
        holder_type   TEXT NOT NULL,
        session_id    TEXT,
        granted_at    BIGINT NOT NULL,
        expires_at    BIGINT NOT NULL,
        ttl_ms        INTEGER NOT NULL,
        status        TEXT NOT NULL DEFAULT 'active'
      );
      CREATE UNIQUE INDEX IF NOT EXISTS idx_leases_active_resource
        ON leases(repository_id, resource)
        WHERE status = 'active';
      CREATE INDEX IF NOT EXISTS idx_leases_expires ON leases(expires_at) WHERE status = 'active';
    `,
  },
];

/**
 * Apply all pending migrations to the PostgreSQL database.
 */
export async function runMigrations(sql: Sql): Promise<void> {
  // Ensure migrations table exists first
  await sql.unsafe(MIGRATIONS[0]!.sql);

  // Find the highest applied migration ID
  const rows = await sql<{ id: number }[]>`
    SELECT id FROM schema_migrations ORDER BY id DESC LIMIT 1
  `;
  const lastApplied = rows[0]?.id ?? 0;

  const pending = MIGRATIONS.filter((m) => m.id > lastApplied);

  if (pending.length === 0) {
    log.info('PostgreSQL schema up to date', { migrations: String(MIGRATIONS.length) });
    return;
  }

  for (const migration of pending) {
    await sql.begin(async (tx) => {
      await tx.unsafe(migration.sql);
      await tx`
        INSERT INTO schema_migrations (id, name, applied_at)
        VALUES (${migration.id}, ${migration.name}, ${Date.now()})
      `;
    });
    log.info(`Applied migration ${migration.id}: ${migration.name}`);
  }

  log.info(`Applied ${String(pending.length)} PostgreSQL migration(s)`);
}
